-- Типы со скриншота методички адаптированы для PostgreSQL.
-- nvarchar(255) -> varchar(255), nvarchar(MAX) -> text, bit -> boolean.
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    due_date DATE,
    completed BOOLEAN
);
